#!/bin/bash
# This command uses the bash shell.
# Author: Jonathan Sterling
# Date last modified: 08 December 2012 
# This command lists the first few lines of all files in the waste bin so that you can check to see if you want to permanently delete them.

if [ -d $HOME/.waste ]                                          # Checks that the directory entered is valid
    then
	for file in $( find $HOME/.waste -maxdepth 1 -name "*" )    # Loops through every file in the .waste directory
    do
    	if [ -f "$file" ]      				                    # Makes sure that it's a file, not a directory.
    	then		
    		head -v -n 5 "$file"    				            # Prints the first 5 lines of the current file.
    	fi
    done
else
    echo You don\'t have a \'.waste\' directory.               # Outputs an error message if there is no .waste directory.
fi
