#!/bin/bash
# This command uses the bash shell.
# Author: Jonathan Sterling
# Date last modified: 08 December 2012 
# This command "takes filenames as its arguments and makes  those files executable to all users."

for var in "$@"                                                 # Loop while "var" is in the total number of inputs.
do
    if [ -f $var ]                                              # If entered file exists.
        then 
        chmod a+x $var                                          # Make it executable for all users.
        succeeded="$succeeded $var"                             # Appends current file to the string "succeeded."
    else
        failed="$failed $var"                                   # Appends current file to the string "failed.2
    fi
done

echo The following files are now exectuable\: $succeeded        # Outputs the files that successfully became executable.

if [ ! -z $failed ]
then
    echo The following files could not be found\: $failed       # Outputs the files that could not be found.
fi
