#!/bin/bash
# This command uses the bash shell.
# Author: Jonathan Sterling
# Date last modified: 08 December 2012 
# This command "takes filenames as its arguments and makes  those files executable to all users."

for var in "$@"                             # loop while var is in the total number of inputs
do
    if [ -f $var ]                          # if entered file exists
        then
        chmod a+x $var                      # make it executable for all users
        succeeded="$succeeded $var"         # appends current file to succeeded
    else
        failed="$failed $var"               # appends current file to failed
    fi
done

echo The following files are now exectuable\: $succeeded     #outputs the files that successfully became executable

if [ ! -z $failed ]
then
    echo The following files could not be found\: $failed        #outputs the files that could not be found
fi
