#!/bin/bash
# This command uses the bash shell.
# Author: Jonathan Sterling
# Date last modified: 08 December 2012 
# This command is a version of rm which only copies files to a special “.waste” directory.

if [ ! -d $HOME/.waste/ ]       	        # Checks whether .waste exists and is a directory.
then
	mkdir $HOME/.waste/      			    # If it doesn't exist, it will make it.
fi

for var in "$@"                             # This will loop while $var is in the total number of inputs.
do
    if [ -f $var ]                          # Checks that the input exists and is a file.
        then
        cp $var $HOME/.waste/               # Copies the input from its' current location to $HOME/.waste.
        succeeded="$succeeded $var"         # Appends the current file to the string "succeeded."
    else
        failed="$failed $var"               # Appends current file to the string "failed."
    fi
done

echo The following files were copied to $HOME/.waste/: $succeeded   # Outputs the files that were successfully copied.

if [ ! -z $failed ]
then
    echo The following files were not found \(if blank, they were all moved successfully\): $failed # Outputs the files that failed to copy
fi


