#!/bin/bash
# This command uses the bash shell.
# Author: Jonathan Sterling
# Date last modified: 09 December 2012 
# This command lists the names of all the files in your waste bin and their size in bytes.

if [ -d $HOME/.waste ]                                          # Checks that the directory entered is valid
    then
    echo "These are the files in your waste directory and their size:"
	for file in $( find $HOME/.waste -maxdepth 1 -name "*" )    # For every file in $HOME/.waste
    do
    	if [ -f "$file" ]      				                    # Makes sure that the current item exists and is a directory.
    	then
            size=$(stat -c%s "$file")                           # Sets size equal to the size of the current file in bytes.
            filename=`basename "$file"`	                        # Removes the location of the file so it just displays the filename.
            echo -e "$filename is $size bytes."                 # Outputs the file name and its' size in bytes.
    	fi
    done

else
    echo "You don't have a $HOME/.waste directory."                     # Output an error message if there's no .waste directory.
fi
