#!/bin/bash
# This command uses the bash shell.
# Author: Jonathan Sterling
# Date last modified: 09 December 2012 
# This command lists the following system information: The users logged on, RAM info, and Linux version info. 

ramInfo=$(free -m)
linuxVersion=$(uname -a)
userInfo=$(who -u)

printf "Here is your RAM info:\n$ramInfo"
printf "\n\nThis is your linux version information:\n$linuxVersion"
printf "\n\nThese are the current users signed in:\n$userInfo"
