#!/bin/bash
# This command uses the bash shell.
testuser=irage
if grep $testuser /etc/passwd
then
    echo The bash files for the user $testuser are:
    ls -a /home/$testuser/.b*
else
    echo No such user $testuser
fi
