#!/bin/bash
# This command uses the bash shell.
# Author: Jonathan Sterling
# Date last modified: 08 December 2012 
# This command reports the number of files in the waste bin.

filecounter=0
wasteDir=$HOME/.waste/


for file in $( find "$wasteDir" -name "*" )    
do
    if [ -f $var ]                          # Checks that the input exists and is a file.
        then    
        filecounter=$[filecounter+1]  
    fi
done

echo There are $filecounter files in the waste directory.
