#!/bin/bash
# This command uses the bash shell.
# Author: Jonathan Sterling
# Date last modified: 08 December 2012 
# This command reports the number of files in the waste bin.

filecounter=0
wasteDir=$HOME/.waste/

if [ ! -d $wasteDir ]						                    # If the $HOME/.waste directory does not exist.
    then
    echo You don\'t have a waste directory.                     # Outputs an error message.

else
    for file in $( find "$wasteDir" -name "*" )                 # For all of the files in .waste
    do
        if [ -f $var ]                                          # Checks that the input exists and is a file.
            then    
            filecounter=$[filecounter+1]                        # Add one to the file count.
     fi
    done
    echo There are $filecounter files in the $HOME/.waste directory.   # Outputs the number of files in the $HOME/.waste directory.
fi


